### ISSUE TITLE
serial_number is really device_id

### ISSUE THREAD

**Issue by MichaelLiss** [jimmykane/easy-fit#17]
Hi again

Just spoke with Garmin:

Elena Kononova (Garmin Health)
May 1, 17:29 CESTOk, 
Seems that we have inconsistent naming, it should be renamed into device id...I see from my internal page that your 'device id' is 3996, which is different from serial number

I think to change that the fit.js should be modified here?

```javascript
    3: { field: 'serial_number', type: 'uint32z', scale: null, offset: '', units: '' },
```

to this:
```javascript
    3: { field: 'device_id', type: 'uint32z', scale: null, offset: '', units: '' },
```

I think this is what should be shown:

```javascript
    "file_id": {
        "device_id": 3996,
        "time_created": "2020-04-30T22:16:48.000Z",
        "manufacturer": "garmin",
        "product": 3113,
        "type": "activity"
    },
```

**Comment by jimmykane** [comment]
If you like you can send a PR :-)

**Comment by MichaelLiss** [comment]
Hello again... 
I was wondering if you have some time to address this ?
I am getting to the point where this issue is starting to block the progress on my project.
(or maybe you could send some instructions on how to modify this so I can update it... and I will try to do the work???)

**Comment by MichaelLiss** [comment]
Hi...

I am going to uninstall your module and use Garmin's parser and an AWS micro-service, as it doesn't seem you are going to work on this any time soon.
