### ISSUE TITLE
Negative temperature value turned into 255

### ISSUE THREAD

**Issue by collax** [jimmykane/easy-fit#23]
Each negative temperature from my fit files are parsed as 255. (Using celsius)

**Comment by jimmykane** [comment]
Should be fixed with the latest Can you validate ?

**Comment by collax** [comment]
Thanks, it work.

**Comment by JuanIrache** [comment]
Hi. This seems to be happening again. I can share a sample privately

**Comment by JuanIrache** [comment]
This seems to have been fixed between NPM versions 1.8.5 and 1.9.0, and then broken again between 1.9.3 and 1.9.4.

I'm not sure what change broke this, as 1.9.3 doesn't seem to be on the main branch as 1.9.4

Edit: It seems this commit that was lost into oblivion fixes this: https://github.com/jimmykane/fit-parser/commit/f4a1255b05ccf4eb29e483e9e47ad3846aa90eff
