### ISSUE TITLE
left_right_balance undefined from SRM PC8 fit file

### ISSUE THREAD

**Issue by joecorkerton** [jimmykane/easy-fit#4]
When parsing any file generated from my PC8 everything seems to work, except the left_right_balance field which returns as undefined. 

Not sure why this would be the case but the data is definitely in there as it can be parsed by Golden Cheetah correctly and it is displayed on the PC8.

![Screenshot 2019-06-16 at 11 25 10](https://user-images.githubusercontent.com/20556001/59562841-802cf680-9029-11e9-8a73-214144483bf3.png)

Seems to be the same issue in the original lib https://github.com/pierremtb/easy-fit/issues/31

**Comment by jimmykane** [comment]
Would you mind giving me the fit file that contains that info ?

**Comment by joecorkerton** [comment]
Here's one example

[2019_04_19_11_12_12.fit.zip](https://github.com/jimmykane/fit-parser/files/3294105/2019_04_19_11_12_12.fit.zip)

**Comment by jimmykane** [comment]
Great, thanks @joecorkerton  I ll give it a look as soon as I can.

**Comment by jimmykane** [comment]
This should be fixed now @joecorkerton  can you validate?

**Comment by joecorkerton** [comment]
@jimmykane I don't see any commits since July 26th?

**Comment by jimmykane** [comment]
I might have not pushed them. Oups. But the module is published. (i am
using now l/r balance)

**Comment by jimmykane** [comment]
When home will see what boo boo i made

**Comment by jimmykane** [comment]
Should be fine now @joecorkerton
