### ISSUE TITLE
Temp is actually in celsius...

### ISSUE THREAD

**Issue by ScottChapman** [jimmykane/easy-fit#7]
I think the fit file format has the temp in celsius. So the calculation to Fahrenheit is not correct...

**Comment by jimmykane** [comment]
hmmmm. Are you sure ? Some example? If I use the unit to Celcius it works.

**Comment by ScottChapman** [comment]
Right, if you look at your code (https://github.com/jimmykane/fit-parser/blob/master/src/fit.js#L24) your multiplier for fahrenheit is `1` and no conversion for Celsius...

```
var fitParser = new FitParser({
    force: true,
    speedUnit: 'mph',
    lengthUnit: 'mi',
    temperatureUnit: 'fahrenheit',
    elapsedRecordField: true,
    mode: 'cascade',
});
```
results in showing my average temp (for a June ride here in MA) a brisk 17

**Comment by jimmykane** [comment]
Yes you are right indeed. :-)

**Comment by jimmykane** [comment]
v1.6.8 contains the commit 6eacf809d546cd9e05c7381b1c8226da43b67e1a that should fix this. 

Would be great if you can validate this

**Comment by ScottChapman** [comment]
works great!
